apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: final1
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce