apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce