apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::908795838523:role/eksctl-clo835-addon-iamserviceaccount-final-Role1-YN97AYNYSZ0C